Makefile: pin `container-device-interface/specs-go@v1.0.0`
Updating to `v1.1.0` causes:

```
 # tags.cncf.io/container-device-interface/pkg/cdi
 Error: vendor/tags.cncf.io/container-device-interface/pkg/cdi/oci.go:62:20: i.EnableCMT undefined (type *IntelRdt has no field or method EnableCMT)
 Error: vendor/tags.cncf.io/container-device-interface/pkg/cdi/oci.go:63:20: i.EnableMBM undefined (type *IntelRdt has no field or method EnableMBM)
```

Signed-off-by: Simon Deziel <simon.deziel@canonical.com>