better error message when CRIU is missing
In the case of migration, you get the following when you don't have CRIU
installed:

error: Error transferring container data: checkpoint failed:
Problem accessing CRIU log: open /tmp/lxd_migration_899480871/dump.log: no such file or directory

Which, while correct, is ugly. Let's give people a better error.

Signed-off-by: Tycho Andersen <tycho.andersen@canonical.com>