profiles: don't mask error message when not found
If we mask this error with the useless "here" prefix, the rest of the error
handling code doesn't figure out that it's a sql.NoRows error, and thus
doesn't propagate the 404 correctly, so we end up with:

$ lxc profile edit host1:invalid
error: here: sql: no rows in result set

Signed-off-by: Tycho Andersen <tycho.andersen@canonical.com>