lxd/instance/lxd-agent: fix selinux fcontext path to lxd-agent /run dir
On most Red Hat systems, you need to use /var/run/XYZ as there is an equivalency rule in SELinux that points /run to it.

Attempting to directly put a rule on /run/XYZ fails with an error:

```
ValueError: File spec /run/lxd_agent/lxd-agent conflicts with equivalency rule '/run /var/run'; Try adding '/var/run/lxd_agent/lxd-agent' instead
```

Signed-off-by: Stéphane Graber <stgraber@stgraber.org>
(cherry picked from commit 8dafa2a41772b22dd1bbb14bd51785eb5fac10ad)
(cherry picked from commit d7f3beb2aaae1a9b39797fa8e723644bacd7e18a)
Signed-off-by: Simon Deziel <simon.deziel@canonical.com>
License: Apache-2.0
(cherry picked from commit e15351966a71967221e4c1c390af8f0590b96afd)