test/suites/basic: avoid `lxd activateifneeded` failures due to LXD being shutdown
If `respawn_lxd` is not called after `shutdown_lxd`, the following `lxd
activateifneeded` call will ultimately fail due to not finding any Unix socket
to wake LXD up:

```
==> Shutting down LXD at /root/lxd2/test/tmp.DSD/l0N (43871)
+ lxd shutdown
...
++ lxd activateifneeded --debug
time="2025-05-20T10:22:46Z" level=warning msg="Instance type not operational" driver=qemu err="QEMU command not available for CPU architecture" type=virtual-machine
time="2025-05-20T10:22:46Z" level=debug msg="Daemon has scheduled volume snapshots, activating..."
time="2025-05-20T10:22:46Z" level=debug msg="Connecting to a local LXD over a Unix socket"
time="2025-05-20T10:22:46Z" level=debug msg="Sending request to LXD" etag= method=GET url="http://unix.socket/1.0"
Error: Get "http://unix.socket/1.0": dial unix /root/lxd2/test/tmp.5SW/PZt/unix.socket: connect: no such file or directory'
```

This failure to connect to LXD is not what we are interested in. What we want
is to check for the `activating` debug message.

Signed-off-by: Simon Deziel <simon.deziel@canonical.com>