test/main: bump `LXD_TMPFS` size for `standalone` on `lvm`
```
==> Setting up networking
++ timeout --foreground 120 /home/runner/go/bin/lxc profile device add default eth0 nic nictype=p2p name=eth0 --verbose
Device eth0 added to default
+ '[' false = true ']'
+ local storage_pool storage_volume
++ basename /tmp/lxd-test.tmp.WH3Y/K1D
+ storage_pool=lxdtest-K1D-pool
+ storage_volume=lxdtest-K1D-pool-vol
+ lxc storage create lxdtest-K1D-pool lvm
++ timeout --foreground 120 /home/runner/go/bin/lxc storage create lxdtest-K1D-pool lvm --verbose
Error: Insufficient free space to create default sized 5GiB pool
+ cleanup
...

==> FAILED TEST: storage (storage)
==> Test result: failure
```

Signed-off-by: Simon Deziel <simon.deziel@canonical.com>
(cherry picked from commit 3f7afd4606674014182b19df99a7d110a5d69e0f)