lxc/config/file: include path to bogus or missing file in errors
@paride reported this error which was tracked down to a corrupted `lxc` config:

```
$ lxc version
Error: Unable to decode the configuration: yaml: line 150: did not find expected key
```

Signed-off-by: Simon Deziel <simon.deziel@canonical.com>