dir: limit pool creation
lxc storage create pool1 dir source=/path-somewhere-under-${LXD_DIR}-but-not-under-storage-pools-subdir
- This is considered invalid (As it might mess with LXD's on-disk layout).
  The following error message is given:

	chb@conventiont|~/source/go/src/github.com/lxc/lxd|2017-03-05/btrfs_improvements *$%>
	> lxc storage create pool1 dir source=/home/chb/mnt/l1/storage-pools
	error: DIR storage pool requests in LXD directory "/home/chb/mnt/l1" are only valid under "/home/chb/mnt/l1/storage-pools"
	(e.g. source=/home/chb/mnt/l1/storage-pools/pool1)

  I really wouldn't want to allow users to create storage pools under say e.g.
  ${LXD_DIR}/{containers,snapshots,images} or the like. This will just cause
  trouble.

Closes #3023.

Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>