Revert "configure: no need to escape Apparmor for that hook"
This reverts commit 04bacb90848246baf567ce5f3fea59e15f1948d2.

As found by Din, changing the group fails if configure is still confined:

```
$ sudo snap install lxd --channel=latest/edge
$ sudo snap set lxd daemon.group=adm
error: cannot perform the following tasks:
- Run configure hook of "lxd" snap (run hook "configure": chgrp: changing group of '/var/snap/lxd/common/lxd/unix.socket': Operation not permitted)
```

Reported-by: Din Music <din.music@canonical.com>
Signed-off-by: Simon Deziel <simon.deziel@canonical.com>