lxd/firewall/drivers: Fix nft syntax
This fixes the `nft` syntax, as it causes the following error in LXD:

```
EROR[05-11|18:09:29] Firewall nftables unable to parse existing ruleset:
invalid character '^' looking for beginning of value
```

When running the command in a shell, it says:

```
$ nft list ruleset --json -nn
Error: syntax error, options must be specified before commands
nft list ruleset --json -nn
   ^             ~~
```

Signed-off-by: Thomas Hipp <thomas.hipp@canonical.com>