lxd/storage/drivers/zfs: suggest `zfs.external` if in snap and ZFS tools are missing
ATM, if no `zpool` of the right version can be found in the LXD snap, this
error is displayed:

```
root@v1:~# lxc storage create zfs zfs
Error: Required tool 'zpool' is missing
```

There is also a more verbose error logged by the snap'ed daemon but it requires
the user to look at `journalctl -u snap.lxd.daemon'.

Make the workaround more easily discoverable by tweaking the error message.

Signed-off-by: Simon Deziel <simon.deziel@canonical.com>
(cherry picked from commit 9952ef8af16f4350fdccd3699c80325931bb484f)