btrfs: handle custom subvolume paths
This improves handling:

1. lxc storage create pool1 source=/path/to/subvolume
- create /path/to/subvolume if it doesn't already exist and bind-mount onto
  ${LXD_DIR}/storage-pools/pool1

2. lxc storage create pool1 source=${LXD_DIR}/storage-pools/pool1
  - create subvolume if LXD is located on btrfs

3. lxc storage create pool1 source=/path-somewhere-under-${LXD_DIR}-but-not-under-storage-pools-subdir
  - This is considered invalid (As it might mess with LXD's on-disk layout).
    The following error message is given:

	chb@conventiont|~/source/go/src/github.com/lxc/lxd|2017-03-05/btrfs_improvements *$%>
	> lxc storage create pool1 btrfs source=/home/chb/mnt/l1/storage-pools/
	error: BTRFS subvolumes requests in LXD directory "/home/chb/mnt/l1" are only valid under "/home/chb/mnt/l1/storage-pools"
	(e.g. source=/home/chb/mnt/l1/storage-pools/pool1)

    I really wouldn't want to allow users to create subvolumes under say e.g.
    ${LXD_DIR}/containers or the like. This will just cause trouble.

Closes #3020.

Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>