lxd/storage/drivers/btrfs: Move subvolumes after reception
Subvolumes were set read-write, and moved right after they were
received. This does not work when doing a refresh as btrfs would return
the error

    ERROR: cannot find parent subvolume

This error would appear after setting the received volume read-write,
before all volumes were received.

The new behaviour is that all subvolumes are received and kept readonly.
The copy operations are recorded and will be performed after the last
subvolume has been received.

Signed-off-by: Thomas Hipp <thomas.hipp@canonical.com>