driver_qemu: don't use romfile for non-x86 architectures
Lxd-pkg snap commit 0ad93fea298c ("qemu: use advanced grammar to prime just
the needed FW") removed file efi-virtio.rom from the LXD snap except on
x86. On non-x86 architectures this caused an error

    Failed setting up device via monitor:
    Failed setting up device "eth0":
    Failed adding NIC device:
    GenericError: failed to find romfile "efi-virtio.rom"

QEMU hard codes that the virtio-net-pci driver uses efi-virtio.rom as
ROM file on all architectures though that file contains only x86 code.

Don't use it on other architectures.

Signed-off-by: Heinrich Schuchardt <heinrich.schuchardt@canonical.com>