test/suites/database: avoid trying to set `user.propX`
The out of space condition is already tested by the prior loop that breaks out
when setting `user.prop${i}` fails. As such, there is no point in trying 2 more
times. Add a quick check to ensure the failure happened during the loop.

Keep attempting to set `user.propY` as dqlite behaves differently when failing
midway (`user.prop7` below) vs from the get go with `user.propY` where several
attempts are made:

```
+ timeout --foreground 120 /root/go/bin/lxc config set c user.prop7 - --verbose
Error: Failed to update database: leader exec failed
+ break
+ '[' 7 -lt 20 ']'
+ lxc config set c user.propY -
+ timeout --foreground 120 /root/go/bin/lxc config set c user.propY - --verbose
WARNING[2026-01-06T22:30:03Z] Dqlite: attempt 1: server 1: no known leader
WARNING[2026-01-06T22:30:03Z] Dqlite: attempt 2: server 1: no known leader
WARNING[2026-01-06T22:30:04Z] Dqlite: attempt 3: server 1: no known leader
WARNING[2026-01-06T22:30:05Z] Dqlite: attempt 4: server 1: no known leader
WARNING[2026-01-06T22:30:06Z] Dqlite: attempt 5: server 1: no known leader
WARNING[2026-01-06T22:30:07Z] Dqlite: attempt 6: server 1: no known leader
WARNING[2026-01-06T22:30:08Z] Dqlite: attempt 7: server 1: no known leader
WARNING[2026-01-06T22:30:09Z] Dqlite: attempt 8: server 1: no known leader
WARNING[2026-01-06T22:30:10Z] Failed to delete operation                    class=task description="Updating images" err="leader exec failed" operation=f46c7adc-ed09-4a52-97c2-282bed579c44 project= status=Success
WARNING[2026-01-06T22:30:10Z] Dqlite: attempt 1: server 1: no known leader
...
WARNING[2026-01-06T22:30:16Z] Transaction timed out. Retrying once          err="Failed to begin transaction: context deadline exceeded" member=1
...
WARNING[2026-01-06T22:30:18Z] Dqlite: attempt 6: server 1: no known leader
WARNING[2026-01-06T22:30:19Z] Dqlite: attempt 7: server 1: no known leader
WARNING[2026-01-06T22:30:20Z] Transaction timed out. Retrying once          err="Failed to begin transaction: context deadline exceeded" member=1
WARNING[2026-01-06T22:30:20Z] Dqlite: attempt 8: server 1: no known leader
WARNING[2026-01-06T22:30:21Z] Failed to delete operation                    class=task description="Updating instance" err="leader exec failed" operation=1c1c745f-f41a-4e0e-ba03-e646d300f304 project=default status=Success
WARNING[2026-01-06T22:30:21Z] Dqlite: attempt 1: server 1: no known leader
...
WARNING[2026-01-06T22:30:24Z] Dqlite: attempt 5: server 1: no known leader
WARNING[2026-01-06T22:30:25Z] Failed to delete operation                    class=task description="Cleaning up expired backups" err="leader exec failed" operation=b8c728d7-d1c2-4e43-b972-4f9c4a7c1a35 project= status=Success
WARNING[2026-01-06T22:30:25Z] Dqlite: attempt 1: server 1: no known leader
...
WARNING[2026-01-06T22:30:27Z] Dqlite: attempt 5: server 1: no known leader
Error: failed to add "Updating instance" Operation 608bebef-51e2-4317-a4f8-9f47c37fa363 to database: leader exec failed
```

Signed-off-by: Simon Deziel <simon.deziel@canonical.com>