edk2-vars-generator/UEFI/Qemu.py: correct QemuEfiFlashSize
Add missing parentheses to avoid an error

    TypeError: unable to increment <class 'enum.auto'>

when running ./edk2-vars-generator --help.

Fixes: 3e4c24ee2b86 ("qemu-ovmf-secureboot: Move to edk2-vars-generator")
Signed-off-by: Heinrich Schuchardt <heinrich.schuchardt@canonical.com>