github: the LXD-UI tests also need the optional runtime deps
```
+ sudo -E lxc storage create default zfs
Installing LXD snap, please be patient.
Error: Required tool "zpool" is missing
```

While `lvm2` is already part of the default package list on GHA runners,
`zfsutils-linux` is not.

Signed-off-by: Simon Deziel <simon.deziel@canonical.com>
(cherry picked from commit 3e2023c4f664ae0e08602bc2f02ab61d44c5a57e)