test/main: check for `setfattr`
Running the tests on a freshly created local machine showed this missing dep:

```
root@v2:~/lxd/test# ./main.sh warnings
==> Checking for dependencies
==> Available storage backends: dir
==> Using storage backend dir
==> Setting up directory backend in /root/lxd/test/tmp.rRe/fnT
==> Spawning lxd in /root/lxd/test/tmp.rRe/fnT
==> Spawned LXD (PID is 21877)
==> Confirming lxd is responsive (PID is 21877)
Error: exec: "setfattr": executable file not found in $PATH
```

Signed-off-by: Simon Deziel <simon.deziel@canonical.com>
(cherry picked from commit 7438e8937f590d7621eeccc4422d31c7078f0628)