add steps to verify lxd host support for vms
Currently tutorial provide steps to create both container and virtual
machine instances. But it doesn't verify lxd host support for kvm
virtualization. Due to this if user try to create a virtual machine on a
non-supported lxd host following error will be prompted.

```
Launching ubuntu-vm
Error: Failed instance creation: No suitable cluster member could be found
```

This change will add additional steps to the tutorial to validate
supported instance types in the LXD environment using 'lxc info' command.

Signed-off-by: pamudithaA <pamuditha.abeysekara@canonical.com>