test/suites/storage: do not fail due to existing pool
A few lines before trying to feed an invalid loop file, we already created a pool named `lxdtest-...-pool1`:

```
++ timeout --foreground 120 /root/go/bin/lxc storage create lxdtest-eU1BHJOwk-pool1 zfs --verbose
Storage pool lxdtest-eU1BHJOwk-pool1 created
++ mktemp -p /tmp/lxd-test.tmp.YOiC/eU1BHJOwk XXXXXXXXX
+ INVALID_LOOP_FILE=/tmp/lxd-test.tmp.YOiC/eU1BHJOwk/dZjDjMJE1-invalid-loop-file
++ basename /tmp/lxd-test.tmp.YOiC/eU1BHJOwk
+ lxc storage create lxdtest-eU1BHJOwk-pool1 zfs source=/tmp/lxd-test.tmp.YOiC/eU1BHJOwk/dZjDjMJE1-invalid-loop-file
++ timeout --foreground 120 /root/go/bin/lxc storage create lxdtest-eU1BHJOwk-pool1 zfs source=/tmp/lxd-test.tmp.YOiC/eU1BHJOwk/dZjDjMJE1-invalid-loop-file --verbose
Error: Storage pool "lxdtest-eU1BHJOwk-pool1" already exists
```

Now with a non-clashing pool name, fails for the right reason:

```
+ lxc storage create lxdtest-A4CA7acLS-pool1 zfs
++ timeout --foreground 120 /root/go/bin/lxc storage create lxdtest-A4CA7acLS-pool1 zfs --verbose
Storage pool lxdtest-A4CA7acLS-pool1 created
++ mktemp -p /tmp/lxd-test.tmp.2pM0/A4CA7acLS XXXXXXXXX
+ INVALID_LOOP_FILE=/tmp/lxd-test.tmp.2pM0/A4CA7acLS/Fm6WfS5Ol-invalid-loop-file
++ basename /tmp/lxd-test.tmp.2pM0/A4CA7acLS
+ lxc storage create lxdtest-A4CA7acLS-invalid-loop-file zfs source=/tmp/lxd-test.tmp.2pM0/A4CA7acLS/Fm6WfS5Ol-invalid-loop-file
++ timeout --foreground 120 /root/go/bin/lxc storage create lxdtest-A4CA7acLS-invalid-loop-file zfs source=/tmp/lxd-test.tmp.2pM0/A4CA7acLS/Fm6WfS5Ol-invalid-loop-file --verbose
Error: Custom loop file locations are not supported
```

Signed-off-by: Simon Deziel <simon.deziel@canonical.com>