github: GHA runners no longer have ephemeral disks
The ephemeral disks are long gone but it seems like it worked for a while even
with the Ceph overhead. It doesn't anymore so let's free space unconditionally
for storage tests.

```
==> Checking VM can be refreshed remotely (different storage pool)
+ lxc snapshot v1
+ lxc copy v1 localhost:v2 --refresh -s vmpool-ceph-154732
Error: Failed instance creation: Error transferring instance data: Failed migration on target: Failed creating instance on target: Failed running: nice -n19 dd if=/var/snap/lxd/common/lxd/storage-pools/vmpool-ceph-154732/virtual-machines/v2/root.img of=/var/snap/lxd/common/lxd/storage-pools/vmpool-ceph-154732/virtual-machines-snapshots/v2/snap1/root.img bs=16M conv=nocreat iflag=direct oflag=direct: exit status 1 (dd: error writing '/var/snap/lxd/common/lxd/storage-pools/vmpool-ceph-154732/virtual-machines-snapshots/v2/snap1/root.img': No space left on device
```

Same as done in [`lxd-ci`](https://github.com/canonical/lxd-ci/commit/d14a971ae9b148cba825dcef8cfa4ba4e1d89343).

Signed-off-by: Simon Deziel <simon.deziel@canonical.com>