UserAuthServerCert: don't ask user to validate already-stored server cert
This way we can pre-store the server certificate and do a
noninteractive lxc remote add.  If the existing certificate
were not valid, the connection will have been refused, giving
an error of:

error: Server certificate has changed

so that this should be safe.

Signed-off-by: Serge Hallyn <serge.hallyn@ubuntu.com>