lxd/device/bic/bridged: Fixes openvswitch port leak when device is stopped
Port was not being detached from bridge on stop causing disconnected ports to accumulate on bridge:

 sudo ovs-vsctl show
 84593e35-9a66-45ba-b647-929e396b3a59
    Bridge lxdbr1
        Port lxdbr1
            Interface lxdbr1
                type: internal
        Port veth1d5cd6a9
            Interface veth1d5cd6a9
                error: "could not open network device veth1d5cd6a9 (No such device)"

Signed-off-by: Thomas Parrott <thomas.parrott@canonical.com>