test/suites/clustering: Remove testing for false positives due to bug in LXD
The test was hiding the following error message:
Error: Device validation failed for "webbaz": Failed loading "custom/webbaz2" from project "default": Storage volume not found

And this error was caused by writing the updated vol device name to the DB after updating the devices.

Signed-off-by: Julian Pelizäus <julian.pelizaeus@canonical.com>
(cherry picked from commit fc69191b141618b128d1cdaa6dd54241cb8c973c)