lxd/cluster/config: reject `acme.ca_url` not using HTTPS
This avoids failing in the `lego` module that enforces HTTPS:

```
$ lxc set acme.agree_tos=true acme.ca_url=http://127.0.0.1:51611/directory acme.domain=example.com acme.email=coyote@acme.example.com
INFO   [2026-03-13T19:58:26Z] Starting automatic server certificate renewal check
ERROR  [2026-03-13T19:58:26Z] Failed server certificate renewal             err="Failed to create new client: get directory at 'http://127.0.0.1:51611/directory': Get \"http://127.0.0.1:51611/directory\": HTTPS is required: http://127.0.0.1:51611/directory"
WARNING[2026-03-13T19:58:26Z] Failure for operation                         class=task description="Renewing server certificate" err="Failed to create new client: get directory at 'http://127.0.0.1:51611/directory': Get \"http://127.0.0.1:51611/directory\": HTTPS is required: http://127.0.0.1:51611/directory" operation=019ce8c7-61d6-7ed5-8194-0932336fc9e8 project=
Error: Failed to create new client: get directory at 'http://127.0.0.1:51611/directory': Get "http://127.0.0.1:51611/directory": HTTPS is required: http://127.0.0.1:51611/directory
```

This requirement is clearly stated in the RFC 8555, section 6.1:
https://www.rfc-editor.org/rfc/rfc8555#section-6.1

Signed-off-by: Simon Deziel <simon.deziel@canonical.com>