compare IPs more intelligently
The symptom of this bug was that if you try to set the https port twice,
you get:

$ lxc config set core.https_address 0.0.0.0:8443
error: cannot listen on https socket: listen tcp 0.0.0.0:8443: bind: address already in use

We can't just use ip.Addr.String here, since we stick 0.0.0.0 in as [::] in
the db some cases. Instead, let's use a more intelligent comparison
mechanism.

Further, there seems to be a small issue with the intelligent comparison
mechanism in the stdlib, so let's agument that.

Signed-off-by: Tycho Andersen <tycho.andersen@canonical.com>