lxd/device/disk: reject `io.threads` setting on containers
```
$ lxc init ubuntu-minimal-daily:24.04 c1
Creating c1
$ lxc config device add c1 tmp disk source=/tmp path=/root/tmp io.bus=nvme   # Good, io.bus is properly rejected
Error: Invalid devices: Device validation failed for "tmp": IO bus configuration cannot be applied to containers
$ lxc config device add c1 tmp disk source=/tmp path=/root/tmp io.threads=32 # Should not have worked
Device tmp added to c1
```

Signed-off-by: Simon Deziel <simon.deziel@canonical.com>
(cherry picked from commit 5d79de3cdb3916ffe5286b60117a813a7bf5e9ff)